version: "3.8"

services:
  # Serviço Laravel (PHP + Composer)
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: mind_cat_api
    volumes:
      - ..:/var/www/html
    ports:
      - "9000:9000" # porta PHP-FPM
    depends_on:
      - mysql
    networks:
      - app-network

  # Serviço MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_db_mindcat
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mind_cat_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mind_cat_db
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_server_mindcat
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge